# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/product.proto\x12\x07product\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"#\n\x15GetProductByIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x12GetProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"1\n\x12GetProductsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"D\n\x13GetProductsResponse\x12-\n\x08products\x18\x01 \x03(\x0b\x32\x1b.product.GetProductResponse2\xa9\x01\n\x0eProductService\x12M\n\x0eGetProductByID\x12\x1e.product.GetProductByIDRequest\x1a\x1b.product.GetProductResponse\x12H\n\x0bGetProducts\x12\x1b.product.GetProductsRequest\x1a\x1c.product.GetProductsResponseB\x19Z\x17product/proto/productpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027product/proto/productpb'
  _globals['_PRODUCT']._serialized_start=32
  _globals['_PRODUCT']._serialized_end=82
  _globals['_GETPRODUCTBYIDREQUEST']._serialized_start=84
  _globals['_GETPRODUCTBYIDREQUEST']._serialized_end=119
  _globals['_GETPRODUCTRESPONSE']._serialized_start=121
  _globals['_GETPRODUCTRESPONSE']._serialized_end=176
  _globals['_GETPRODUCTSREQUEST']._serialized_start=178
  _globals['_GETPRODUCTSREQUEST']._serialized_end=227
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=229
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=297
  _globals['_PRODUCTSERVICE']._serialized_start=300
  _globals['_PRODUCTSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
